In [1]:
import numpy

In [3]:
numpy.__version__

'1.15.4'

In [4]:
import numpy as np

In [7]:
np?

In [14]:
var1= 10

In [15]:
for i in range(var1):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [17]:
var2= list(range(1,10))

In [18]:
var2

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [19]:
type(var2)

list

In [20]:
import array

In [21]:
var3 = array.array('i',var2)

In [22]:
var3

array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [27]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
np.full((3,8),9)

array([[9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9]])

In [29]:
np.arange(0,100,20)

array([ 0, 20, 40, 60, 80])

In [31]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [35]:
np.random.random((2,2))

array([[0.0853066 , 0.63746748],
       [0.33015517, 0.02327009]])

In [36]:
np.random.randint(0,10,(3,3))

array([[6, 2, 1],
       [0, 1, 2],
       [7, 8, 9]])

In [37]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
np.empty((2,2))

array([[0.0853066 , 0.63746748],
       [0.33015517, 0.02327009]])

In [41]:
np.random.seed(10)

In [43]:
a= np.random.random((3,3))

In [44]:
a

array([[0.77132064, 0.02075195, 0.63364823],
       [0.74880388, 0.49850701, 0.22479665],
       [0.19806286, 0.76053071, 0.16911084]])

In [45]:
a.ndim

2

In [46]:
a.shape

(3, 3)

In [47]:
a.size

9

In [48]:
print("dtype",a.shape)

dtype (3, 3)


In [50]:
a[2,1]

0.7605307121989587

In [51]:
a[1,1]

0.4985070123025904

In [55]:
for i in range(3):
    for j in range(3):
        print(a[i,j])
        print (i,j)
        

0.771320643266746
0 0
0.0207519493594015
0 1
0.6336482349262754
0 2
0.7488038825386119
1 0
0.4985070123025904
1 1
0.22479664553084766
1 2
0.19806286475962398
2 0
0.7605307121989587
2 1
0.16911083656253545
2 2


In [57]:
var = np.arange(20)

In [58]:
var

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [59]:
var[4:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [60]:
var[:4]

array([0, 1, 2, 3])

In [61]:
var[5:9]

array([5, 6, 7, 8])

In [62]:
var[::1]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [63]:
var[::5]

array([ 0,  5, 10, 15])

In [64]:
var[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

In [65]:
var[::-2]

array([19, 17, 15, 13, 11,  9,  7,  5,  3,  1])

In [66]:
np.append(var,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [67]:
 var

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [68]:
var1

10

In [74]:
ndarr = np.random.random((3,3))

In [75]:
ndarr

array([[0.08833981, 0.68535982, 0.95339335],
       [0.00394827, 0.51219226, 0.81262096],
       [0.61252607, 0.72175532, 0.29187607]])

In [76]:
ndarr[:1,:1]

array([[0.08833981]])

In [77]:
ndarr[:2,1:]

array([[0.68535982, 0.95339335],
       [0.51219226, 0.81262096]])

In [78]:
ndarr[::,::]

array([[0.08833981, 0.68535982, 0.95339335],
       [0.00394827, 0.51219226, 0.81262096],
       [0.61252607, 0.72175532, 0.29187607]])

In [81]:
ndarr[::-1,::-3]

array([[0.29187607],
       [0.81262096],
       [0.95339335]])

In [83]:
ndarr[:,1]

array([0.68535982, 0.51219226, 0.72175532])

In [84]:
ndarr[0,:]

array([0.08833981, 0.68535982, 0.95339335])

In [85]:
a = np.arange(10)

In [86]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
a.reshape(3,3)

ValueError: cannot reshape array of size 10 into shape (3,3)

In [97]:
b=[1,2,3,4,5,6,7,8,9]

In [96]:
x=[1,2,3,4,5,6,7,8,9]

In [92]:
np.delete(a,9,0)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [94]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
a.size

10

In [98]:
x1, b1 = np.array(x), np.array(b)

In [99]:
x1,b1

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [105]:
x1b1 = np.concatenate([x1,b1])

In [106]:
x1b1

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:
x1,x2,x3 = np.split(x1b1,[2,7])

In [108]:
x1,x2,x3

(array([1, 2]),
 array([3, 4, 5, 6, 7]),
 array([8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [109]:
np.random.seed(0)

In [111]:
def cmpt_re(val):
    op = np.empty(len(val))
    for i in range(len(val)):
        op[i] = 1.0/val[i]
    return op

val = x2
x2
cmpt_re(x2)

array([0.33333333, 0.25      , 0.2       , 0.16666667, 0.14285714])

In [113]:
%timeit a=5

13.3 ns ± 0.0817 ns per loop (mean ± std. dev. of 7 runs, 100000000 loops each)


In [115]:
%timeit cmpt_re(x2)

16.9 µs ± 115 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [116]:
print(cmpt_re(x2))

[0.33333333 0.25       0.2        0.16666667 0.14285714]


In [121]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap